version: ">= 0.14.0"

formatter: markdown table

content: |-
  # SDWAN Banner Feature Template Example
  To run this example you need to execute:
  ```bash
  $ terraform init
  $ terraform plan
  $ terraform apply
  ```
  Note that this example will create resources. Resources can be destroyed with `terraform destroy`.

  #### `banner_feature_template.yaml`

  ```yaml
  {{ include "./banner_feature_template.yaml" }}
  ```

  #### `main.tf`

  ```hcl
  {{ include "./main.tf" }}
  ```
output:
  file: README.md
  mode: replace
